Starting mismatch_tf_test100.py...
Files already downloaded and verified
Files already downloaded and verified
[Epoch 1] Loss: 2.1474
[Epoch 2] Loss: 2.0165
[Epoch 3] Loss: 1.9237
[Epoch 4] Loss: 1.8371
[Epoch 5] Loss: 1.7774
[Epoch 6] Loss: 1.7387
[Epoch 7] Loss: 1.6685
[Epoch 8] Loss: 1.6106
[Epoch 9] Loss: 1.5422
[Epoch 10] Loss: 1.5115
[Epoch 11] Loss: 1.4554
[Epoch 12] Loss: 1.3998
[Epoch 13] Loss: 1.3356
[Epoch 14] Loss: 1.2863
[Epoch 15] Loss: 1.2400
[Epoch 16] Loss: 1.1866
[Epoch 17] Loss: 1.1423
[Epoch 18] Loss: 1.0848
[Epoch 19] Loss: 1.0737
[Epoch 20] Loss: 1.0444
[Epoch 21] Loss: 0.9999
[Epoch 22] Loss: 0.9828
[Epoch 23] Loss: 0.9336
[Epoch 24] Loss: 0.9263
[Epoch 25] Loss: 0.8917
[Epoch 26] Loss: 0.8778
[Epoch 27] Loss: 0.8404
[Epoch 28] Loss: 0.8123
[Epoch 29] Loss: 0.8047
[Epoch 30] Loss: 0.7697
[Epoch 31] Loss: 0.7368
[Epoch 32] Loss: 0.7172
[Epoch 33] Loss: 0.7087
[Epoch 34] Loss: 0.6847
[Epoch 35] Loss: 0.6884
[Epoch 36] Loss: 0.6378
[Epoch 37] Loss: 0.6219
[Epoch 38] Loss: 0.6158
[Epoch 39] Loss: 0.5784
[Epoch 40] Loss: 0.5872
[Epoch 41] Loss: 0.5738
[Epoch 42] Loss: 0.5709
[Epoch 43] Loss: 0.5391
[Epoch 44] Loss: 0.5266
[Epoch 45] Loss: 0.5225
[Epoch 46] Loss: 0.4867
[Epoch 47] Loss: 0.5111
[Epoch 48] Loss: 0.4940
[Epoch 49] Loss: 0.4478
[Epoch 50] Loss: 0.4464
[Epoch 51] Loss: 0.4006
[Epoch 52] Loss: 0.4264
[Epoch 53] Loss: 0.3900
[Epoch 54] Loss: 0.3819
[Epoch 55] Loss: 0.3684
[Epoch 56] Loss: 0.3670
[Epoch 57] Loss: 0.3392
[Epoch 58] Loss: 0.3566
[Epoch 59] Loss: 0.3777
[Epoch 60] Loss: 0.3270
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
[Epoch 1] Loss: 4.4964
[Epoch 2] Loss: 4.3244
[Epoch 3] Loss: 4.2504
[Epoch 4] Loss: 4.1748
[Epoch 5] Loss: 4.0908
[Epoch 6] Loss: 4.0260
[Epoch 7] Loss: 3.9455
[Epoch 8] Loss: 3.9004
[Epoch 9] Loss: 3.8238
[Epoch 10] Loss: 3.7650
[Epoch 11] Loss: 3.7230
[Epoch 12] Loss: 3.6669
[Epoch 13] Loss: 3.6129
[Epoch 14] Loss: 3.5729
[Epoch 15] Loss: 3.5300
[Epoch 16] Loss: 3.4602
[Epoch 17] Loss: 3.4132
[Epoch 18] Loss: 3.3698
[Epoch 19] Loss: 3.3321
[Epoch 20] Loss: 3.2845
[Epoch 21] Loss: 3.2353
[Epoch 22] Loss: 3.1783
[Epoch 23] Loss: 3.1479
[Epoch 24] Loss: 3.1303
[Epoch 25] Loss: 3.0806
[Epoch 26] Loss: 3.0166
[Epoch 27] Loss: 2.9618
[Epoch 28] Loss: 2.9182
[Epoch 29] Loss: 2.8882
[Epoch 30] Loss: 2.8323
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1729647327489/work/aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/ubuntu/repaug/mismatch_tf_test100.py", line 166, in <module>
    main()
  File "/home/ubuntu/repaug/mismatch_tf_test100.py", line 114, in main
    train_linear_prob(lp, raw_loader, num_epochs_student, device)
  File "/home/ubuntu/repaug/train_eval_test100.py", line 40, in train_linear_prob
    running_loss += loss.item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

mismatch_tf_test100.py failed with exit status 1.
