Starting noise.py...
Files already downloaded and verified
Files already downloaded and verified

=== Pretraining External Model (BigCNN) on 10k Random (Corrupted) Samples ===
[Epoch 1] Loss: 2.3032
[Epoch 2] Loss: 2.3032
[Epoch 3] Loss: 2.3034
[Epoch 4] Loss: 2.3032
[Epoch 5] Loss: 2.3033
[Epoch 6] Loss: 2.3034
[Epoch 7] Loss: 2.3029
[Epoch 8] Loss: 2.3031
[Epoch 9] Loss: 2.3033
[Epoch 10] Loss: 2.3031
[Epoch 11] Loss: 2.3032
[Epoch 12] Loss: 2.3034
[Epoch 13] Loss: 2.3036
[Epoch 14] Loss: 2.3032
[Epoch 15] Loss: 2.3029
[Epoch 16] Loss: 2.3037
[Epoch 17] Loss: 2.3030
[Epoch 18] Loss: 2.3029
[Epoch 19] Loss: 2.3029
[Epoch 20] Loss: 2.3034
[Epoch 21] Loss: 2.3031
[Epoch 22] Loss: 2.3029
[Epoch 23] Loss: 2.3030
Traceback (most recent call last):
  File "/home/ubuntu/repaug/noise.py", line 180, in <module>
    main()
  File "/home/ubuntu/repaug/noise.py", line 81, in main
    train_model(external_model, pretrain_loader, pretrain_epochs, device)
  File "/home/ubuntu/repaug/train_eval.py", line 19, in train_model
    for inputs, labels in train_loader:
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1448, in _next_data
    idx, data = self._get_data()
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1412, in _get_data
    success, data = self._try_get_data()
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1243, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/ubuntu/miniconda3/envs/repaug/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
